package com.dukascopy.connect.sys.style.presets
{
	import assets.AttachCamIcon;
	import assets.AttachFileDark;
	import assets.AttachFileIcon;
	import assets.AttachImageIcon;
	import assets.AttachInvoiceIcon;
	import assets.AttachPayIcon;
	import assets.ContectDeleteIcon;
	import assets.CreateDealIcon;
	import assets.FilterSmallIcon;
	import assets.FingerprintInfo;
	import assets.JailIcon;
	import assets.JailIconRound;
	import assets.LoginLogo;
	import assets.PaidChatIcon;
	import assets.PaymentsImageWhite;
	import assets.PaymentsLogo;
	import assets.ProtectionIcon;
	import assets.SendGiftIcon;
	import assets.TouchIdIcon;
	import assets.TransferIllustration;
	import assets.VisaClip;
	import com.dukascopy.connect.Config;
	import com.dukascopy.connect.sys.style.Style;
	import white.Add;
	import white.Attach;
	import white.Back;
	import white.Ban;
	import white.BanForever;
	import white.Bank;
	import white.BlockUser;
	import white.Bot;
	import white.ChatIcon;
	import white.Community;
	import white.Edit;
	import white.File;
	import white.Flower;
    import com.dukascopy.connect.sys.theme.AppTheme;
	import white.GroupChat;
	import white.Icon911;
	import white.Info;
	import white.Jail;
	import white.Language;
	import white.Location;
	import white.Lock;
	import white.Logout;
	import white.MakeCall;
	import white.Marketplace;
	import white.MenuBank;
	import white.MenuBankSelected;
	import white.MenuBot;
	import white.MenuBotSelected;
	import white.MenuChat;
	import white.MenuChatSelected;
	import white.MenuContacts;
	import white.MenuContactsSelected;
	import white.MenuSettings;
	import white.MenuSettingsSelected;
	import white.Mic;
	import white.Notifications;
	import white.OneClick;
	import white.Phone;
	import white.Protection;
	import white.Rating;
	import white.Referral;
	import white.Refresh;
	import white.Roadmap_approve;
	import white.Roadmap_approve_fail;
	import white.Roadmap_approve_success;
	import white.Roadmap_card;
	import white.Roadmap_card_fail;
	import white.Roadmap_card_success;
	import white.Roadmap_deposit;
	import white.Roadmap_deposit_fail;
	import white.Roadmap_deposit_success;
	import white.Roadmap_form;
	import white.Roadmap_form_fail;
	import white.Roadmap_form_success;
	import white.Roadmap_scan;
	import white.Roadmap_scan_fail;
	import white.Roadmap_scan_success;
	import white.Roadmap_solvency;
	import white.Roadmap_solvency_fail;
	import white.Roadmap_solvency_success;
	import white.Roadmap_verification;
	import white.Roadmap_verification_fail;
	import white.Roadmap_verification_success;
	import white.Send;
	import white.Settings;
	import white.Smile;
	import white.SmileColor;
	import white.Social;
	import white.SoundMessages;
	import white.Stat;
	import white.Sticker;
	import white.StickerColor;
	import white.Unlock;
	import white.VoiceSend;
	import white.Zero;
	import white.Zoom;

	/**
	 * ...
	 * @author Sergey Dobarin
	 */
	public dynamic class PresetWhite extends Preset
	{
		public function PresetWhite()
		{
			this[Style.TOP_BAR] = Color.WHITE;
			this[Style.TOP_BAR_FONT_SIZE] = Config.FINGER_SIZE * .45;
			this[Style.TOP_BAR_TEXT_COLOR] = Color.BLACK_OLD;
			this[Style.TOP_BAR_ICON_COLOR] = Color.GREY;
			this[Style.TOP_BAR_TEXT_BOLD] = true;
			this[Style.FILTER_TABS_COLOR_TAB_BG_SELECTED] = Color.GREY_SSL;
			this[Style.FILTER_TABS_COLOR_TAB_TEXT_SELECTED] = Color.GREY;
			this[Style.FILTER_TABS_COLOR_TAB_BG_BORDER_SELECTED] = Color.GREY_SUPER_LIGHT;
			this[Style.FILTER_TABS_COLOR_TAB_TEXT] = Color.GREY;
			this[Style.FILTER_TABS_COLOR_TAB_BG_BORDER] = Color.GREY_SSL;
			this[Style.TOP_BAR_STATUS_TEXT_COLOR] = Color.GREY;
			this[Style.TOP_BAR_FONT_SIZE_SMALL] = Config.TOP_BAR_FONT_SIZE;
			this[Style.TOP_BAR_TEXT_BOLD_SMALL] = false;
			this[Style.BOTTOM_BAR_COLOR] = Color.GREY_SUPER_LIGHT;
			this[Style.BOTTOM_BAR_LINE] = false;
			this[Style.BOTTOM_BAR_TEXT_COLOR] = Color.GREY;
			this[Style.BOTTOM_BAR_TEXT_SELECTED_COLOR] = Color.RED;
			this[Style.CHAT_BACKGROUND] = 0xE9F3FB;
			this[Style.MESSAGE_COLOR_SELF] = Color.WHITE;
			this[Style.MESSAGE_RADIUS] = Config.FINGER_SIZE * .24;
			this[Style.MESSAGE_DATE_BACK_ALPHA] = 0;
			this[Style.MESSAGE_DATE_COLOR] = Color.GREY;
			this[Style.STATUS_COLOR] = 0xFDFFFF;
			this[Style.COLOR_BACKGROUND] = Color.WHITE;
			this[Style.COLOR_TITLE] = Color.BLACK_OLD;
			this[Style.COLOR_LIST_SELECTED] = Color.WHITE;
			this[Style.COLOR_LIST_SPECIAL] = Color.GREY_SUPER_LIGHT;
			this[Style.COLOR_SUBTITLE] = Color.GREY;
			this[Style.FILTER_TABS_COLOR_BACKGROUND] = Color.WHITE;
			this[Style.COLOR_TIP_BACKGROUND] = Color.GREY_SSL;
			this[Style.COLOR_TIP_TEXT] = Color.GREY;
			this[Style.COLOR_ICON_LIGHT] = Color.GREY_LIGHT;
			this[Style.COLOR_TEXT] = Color.BLACK;
			this[Style.COLOR_SEPARATOR] = Color.GREY_SUPER_LIGHT;
			this[Style.COLOR_SEPARATOR_TOP_BAR] = Color.GREY_SSL;
			this[Style.COLOR_ICON_SETTINGS] = Color.GREY;
			this[Style.TOP_BAR_ICON_SIZE] = Config.FINGER_SIZE * .3;
			this[Style.CHAT_TOP_ICON_SIZE] = .45;
			this[Style.ICON_COLOR] = Color.GREY;
			this[Style.ICON_RIGHT_COLOR] = Color.GREY_LIGHT;
			this[Style.COLOR_BUTTON_RED_DOWN] = Color.RED_DARK;
			this[Style.COLOR_BUTTON_TEXT] = Color.WHITE;
			this[Style.COLOR_BUTTON_RED] = Color.RED;
			this[Style.BANK_BACKGROUND_ID] = "7";
			this[Style.COLOR_CHAT_MESSAGE_BACKGROUND] = Color.WHITE;
			this[Style.COLOR_CHAT_MESSAGE_LINE] = Color.GREY_SUPER_LIGHT;
			this[Style.COLOR_CHAT_MESSAGE_MENU] = Color.RED;
			this[Style.COLOR_INPUT_BACKGROUND] = Color.WHITE;
			this[Style.COLOR_ICON_SPECIAL] = Color.GREY;
			this[Style.COLOR_TIP_BACKGROUND_SPECIAL] = Color.GREY_SSL;
			this[Style.COLOR_LINE] = Color.GREY;
			this[Style.TOGGLER_UNSELECTED] = Color.GREY_LIGHT;
			this[Style.TOGGLER_UNSELECTED_DOWN] = Color.GREY;
			this[Style.COLOR_STICKERS_MENU_BACKGROUND] = 0xECEEEF;
			this[Style.MESSAGE_COLOR] = Color.WHITE;
			this[Style.BOTTOM_BAR_SELECTED_BACKGROUND] = NaN;
			this[Style.COLOR_TIPS_911_BACKGROUND] = 0xF6F7F2;
			this[Style.COLOR_911_BRED] = 0x0000EE;
			this[Style.COLOR_BACKGROUND_LIGHT] = 0xF6F7F2;
			this[Style.COLOR_TIPS] = Color.RED;
			this[Style.COLOR_LINE_LIGHT] = Color.GREY_LIGHT;
			this[Style.COLOR_LINE_SSL] = Color.GREY_SSL;
			this[Style.COLOR_911_MARK_TEXT] = Color.GREY;
			this[Style.COLOR_911_MARK_BACK] = Color.GREY_SSL;
			this[Style.ITALIC_911_MARK_TEXT] = false;
			
			this[Style.COLOR_ROADMAP_ACTIVE] = Color.GREEN;
			this[Style.COLOR_ROADMAP_DONE] = Color.GREEN;
			this[Style.COLOR_ROADMAP_FAIL] = Color.RED;
			this[Style.COLOR_ROADMAP_INACTIVE] = Color.GREY_LIGHT;
			
			this[Style.MENU_CHATS] = white.MenuChat;
			this[Style.MENU_CONTACTS] = white.MenuContacts;
			this[Style.MENU_BANK] = white.MenuBank;
			this[Style.MENU_BOT] = white.MenuBot;
			this[Style.MENU_SETTINGS] = white.MenuSettings;
			this[Style.MENU_CHATS_SELECTED] = white.MenuChatSelected;
			this[Style.MENU_CONTACTS_SELECTED] = white.MenuContactsSelected;
			this[Style.MENU_BANK_SELECTED] = white.MenuBankSelected;
			this[Style.MENU_BOT_SELECTED] = white.MenuBotSelected;
			this[Style.MENU_SETTINGS_SELECTED] = white.MenuSettingsSelected;

			this[Style.ICON_911] = white.Icon911;
			this[Style.ICON_SETTINGS] = white.Settings;
			this[Style.ICON_CALLS] = white.Phone;
			this[Style.ICON_REFRESH] = white.Refresh;
			this[Style.ICON_GROUP_CHAT] = white.GroupChat;

            AppTheme.colorPallete=AppTheme.lightColorPallete;
			Config.TOP_BAR_HEIGHT *= 1.1;
			
			this[Style.LIGHT_STATUS_BAR] = false;

			this[Style.ICON_MARKETPLACE] = white.Marketplace;
			this[Style.ICON_BOT] = white.Bot;
			this[Style.ICON_BANK] = white.Bank;
			this[Style.ICON_LOCK] = white.Lock;
			this[Style.ICON_UNLOCK] = white.Unlock;
			this[Style.ICON_SMILE] = white.Smile;
			this[Style.ICON_ATTACH] = white.Attach;
			this[Style.ICON_SMILE_COLOR] = white.SmileColor;
			this[Style.ICON_MIC] = white.Mic;
			this[Style.ICON_STICKER] = white.Sticker;
			this[Style.ICON_STICKER_COLOR] = white.StickerColor;
			this[Style.ICON_ATTACH_COLOR] = Color.GREY;
			this[Style.ICON_SEND] = white.Send;
			this[Style.ICON_SEND_VOICE] = white.VoiceSend;
			this[Style.ICON_NOTIFICATIONS] = white.Notifications;
			this[Style.ICON_SOUND_MESSAGES] = white.SoundMessages;
			this[Style.ICON_SOUND_CALL] = white.Phone;
			this[Style.ICON_LANGUAGE] = white.Language;
			this[Style.ICON_SOCIAL] = white.Social;
			this[Style.ICON_RATING] = white.Rating;
			this[Style.ICON_REFERRAL] = white.Referral;
			this[Style.ICON_LOGOUT] = white.Logout;
			this[Style.ICON_COMMUNITY] = white.Community;
			this[Style.ICON_JAIL] = white.Jail;
			this[Style.ICON_PROTECTION] = white.Protection;
			this[Style.ICON_PAID_CHAT] = PaidChatIcon;
			this[Style.ICON_ONE_CLICK] = white.OneClick;
			this[Style.ICON_STAT] = white.Stat;
			this[Style.ICON_BLOCK_USER] = white.BlockUser;
			this[Style.ICON_BAN] = white.Ban;
			this[Style.ICON_BAN_FOREVER] = white.BanForever;
			this[Style.ICON_ZERO_RATING] = white.Zero;
			this[Style.ICON_FLOWER] = white.Flower;
			this[Style.ICON_ADD_USER] = white.Referral;
			this[Style.ICON_EDIT] = white.Edit;
			this[Style.ICON_FILE] = white.File;
			this[Style.ICON_BACK] = white.Back;
			this[Style.ICON_MAKE_CALL] = white.MakeCall;
			this[Style.ICON_ZOOM] = white.Zoom;
			this[Style.ICON_INFO] = white.Info;
			this[Style.ICON_ADD] = white.Add;
			this[Style.ICON_GEO] = white.Location;
			this[Style.ICON_ATTACH_CAMERA] = AttachCamIcon;
			this[Style.ICON_ATTACH_GALLERY] = AttachImageIcon;
			this[Style.ICON_ATTACH_MONEY] = AttachPayIcon;
			this[Style.ICON_ATTACH_INVOICE] = AttachInvoiceIcon;
			this[Style.ICON_ATTACH_PUZZLE] = attachIconPuzzle;
			this[Style.ICON_ATTACH_GIFT] = SendGiftIcon;
			this[Style.ICON_ATTACH_VIDEO] = attachIconVideo;
			this[Style.ICON_ARROW_DOWN] = SWFDoubleArrowsDown;
			this[Style.ICON_ARROW_UP] = SWFDoubleArrowsUp;
			this[Style.ICON_JAILED] = JailIcon;
			this[Style.ICON_FILTERS] = FilterSmallIcon;
			this[Style.ICON_CHAT] = white.ChatIcon;
			
			this[Style.ICON_ROADMAP_FORM_ACTIVE] = Roadmap_form;
			this[Style.ICON_ROADMAP_FORM_DONE] = Roadmap_form_success;
			this[Style.ICON_ROADMAP_FORM_FAIL] = Roadmap_form_fail;
			
			this[Style.ICON_ROADMAP_SCAN_ACTIVE] = Roadmap_scan;
			this[Style.ICON_ROADMAP_SCAN_DONE] = Roadmap_scan_success;
			this[Style.ICON_ROADMAP_SCAN_FAIL] = Roadmap_scan_fail;
			
			this[Style.ICON_ROADMAP_SOLVENCY_ACTIVE] = Roadmap_solvency;
			this[Style.ICON_ROADMAP_SOLVENCY_DONE] = Roadmap_solvency_success;
			this[Style.ICON_ROADMAP_SOLVENCY_FAIL] = Roadmap_solvency_fail;
			
			this[Style.ICON_ROADMAP_DEPOSIT_ACTIVE] = Roadmap_deposit;
			this[Style.ICON_ROADMAP_DEPOSIT_DONE] = Roadmap_deposit_success;
			this[Style.ICON_ROADMAP_DEPOSIT_FAIL] = Roadmap_deposit_fail;
			
			this[Style.ICON_ROADMAP_SELECT_CARD_ACTIVE] = Roadmap_card;
			this[Style.ICON_ROADMAP_SELECT_CARD_DONE] = Roadmap_card_success;
			this[Style.ICON_ROADMAP_SELECT_CARD_FAIL] = Roadmap_card_fail;
			
			this[Style.ICON_ROADMAP_VIDEOIDENTIFICATION_ACTIVE] = Roadmap_verification;
			this[Style.ICON_ROADMAP_VIDEOIDENTIFICATION_DONE] = Roadmap_verification_success;
			this[Style.ICON_ROADMAP_VIDEOIDENTIFICATION_FAIL] = Roadmap_verification_fail;
			
			this[Style.ICON_ROADMAP_APPROVE_ACCOUNT_ACTIVE] = Roadmap_approve;
			this[Style.ICON_ROADMAP_APPROVE_ACCOUNT_DONE] = Roadmap_approve_success;
			this[Style.ICON_ROADMAP_APPROVE_ACCOUNT_FAIL] = Roadmap_approve_fail;
			this[Style.ICON_TEXT] = white.Text;
			this[Style.ICON_TOUCH_ID] = TouchIdIcon;
			this[Style.ICON_FACE_ID] = FaceIdIcon;
			this[Style.CONTROL_TEXT_SIZE] = Config.FINGER_SIZE * .3;
			this[Style.CONTROL_TEXT_SMALL_SIZE] = Config.FINGER_SIZE * .25;
			this[Style.SIZE_BUTTON_CORNER] = Config.FINGER_SIZE * .3;
			this[Style.SIZE_BUTTON_HEIGHT] = Config.FINGER_SIZE * .8;
			this[Style.COLOR_TEXT_DISABLE] = Color.GREY_LIGHT;
			this[Style.CONTROL_INACTIVE] = Color.GREY_SSL;
			this[Style.ERROR_COLOR] = Color.RED;
			this[Style.PAYMENTS_LOGIN_IMAGE] = PaymentsImageWhite;
			this[Style.PAYMENTS_LOGIN_BACK_COLOR] = 0xFFE6F5;
			this[Style.COLOR_IOS_ACTION_SHEET_BACK] = 0xFFFFFF;
			this[Style.COLOR_IOS_ACTION_SHEET_ITEM_BACK] = 0xF9F9F9;
			this[Style.ALPHA_IOS_ACTION_SHEET_BACK] = 0.88;
			this[Style.RADIUS_IOS_ACTION_SHEET_BACK] = Config.FINGER_SIZE * .23;
			this[Style.HEIGHT_IOS_ACTION_SHEET_BACK] = Config.FINGER_SIZE * 1.0;
			this[Style.ICON_PAYMENTS_LOGO] = PaymentsLogo;
			this[Style.ICON_LOGIN_LOGO] = LoginLogo;
			this[Style.COLOR_KEYBOARD_TEXT] = Color.BLUE_DARK_2;
			this[Style.COLOR_PHONE] = Color.BLUE_2;
			this[Style.ICON_ATTACH_FILE] = AttachFileIcon;
			this[Style.COLOR_POPUP_HEADER] = Color.GREY_SUPER_LIGHT;
			this[Style.COLOR_BUTTON_SECONDARY] = Color.GREY;
			this[Style.COLOR_TOGGLER] = NaN;
			this[Style.ROADMAP_ILLUSTRATION] = RoadmapImage;
			this[Style.PAYMENT_VISA] = VisaClip;
			this[Style.TRANSFER_ILLUSTRATION] = TransferIllustration;
			this[Style.ICON_ATTACH_DEAL] = CreateDealIcon;
			this[Style.COLOR_BUTTON_OUTLINE] = Color.GREY_LIGHT;
			this[Style.FLOAT_POOPUP_RADIUS] = int(Config.FINGER_SIZE * .6);
			this[Style.BUTTON_PADDING] = int(Config.FINGER_SIZE * .23);
			this[Style.COLOR_BUTTON_ACCENT] = Color.GREY_DARK;
			this[Style.COLOR_SEEK_BACK] = Color.GREY_SSL;
			this[Style.COLOR_TEXT_RED_DARK] = Color.RED_DARK;
			this[Style.COLOR_RED_LIGHT] = Color.RED_LIGHT;
			this[Style.ICON_TRASH] = ContectDeleteIcon;
			this[Style.COLOR_ACCENT_PANEL] = Color.GREY_DARK;
		}
	}
}