package com.dukascopy.connect.sys.style.presets
{
	import assets.AddItemButton;
	import assets.AddUserToChatIcon;
	import assets.AttachCamIcon;
	import assets.AttachFileDark;
	import assets.AttachFileIcon;
	import assets.AttachImageIcon;
	import assets.AttachInvoiceIcon;
	import assets.AttachPayIcon;
	import assets.BlockUserIcon;
	import assets.CommunityIconGrey;
	import assets.ContectDeleteIcon;
	import assets.CreateDealIcon;
	import assets.EditIcon;
	import assets.FilterSmallIcon;
	import assets.FingerprintInfo;
	import assets.FlowerIcon;
	import assets.Icon911;
	import assets.IconGroupChat;
	import assets.IconInfoClip;
	import assets.IconSendFiles;
	import assets.JailIcon;
	import assets.JailIconRound;
	import assets.LoginLogo;
	import assets.OwnerIcon;
	import assets.PaidChatIcon;
	import assets.PaymentsImageWhite;
	import assets.PaymentsLogo;
	import assets.PhoneIconGrey;
	import assets.PhonebookIcon;
	import assets.ProtectionIcon;
	import assets.SendButtonSound;
	import assets.SendGiftIcon;
	import assets.SetLanguagesIcon;
	import assets.SettingsIcon_banForever;
	import assets.StartStreamIcon;
	import assets.TouchIdIcon;
	import assets.TransferIllustration;
	import assets.VisaClip;
	import com.dukascopy.connect.Config;
	import com.dukascopy.connect.sys.style.Style;
	import com.dukascopy.connect.sys.theme.AppTheme;
	import white.ChatIcon;
	import white.Menu911;
	import white.Menu911Selected;
	import white.OneClick;
	import white.Roadmap_approve;
	import white.Roadmap_approve_fail;
	import white.Roadmap_approve_success;
	import white.Roadmap_card;
	import white.Roadmap_card_fail;
	import white.Roadmap_card_success;
	import white.Roadmap_deposit;
	import white.Roadmap_deposit_fail;
	import white.Roadmap_deposit_success;
	import white.Roadmap_form;
	import white.Roadmap_form_fail;
	import white.Roadmap_form_success;
	import white.Roadmap_scan;
	import white.Roadmap_scan_fail;
	import white.Roadmap_scan_success;
	import white.Roadmap_solvency;
	import white.Roadmap_solvency_fail;
	import white.Roadmap_solvency_success;
	import white.Roadmap_verification;
	import white.Roadmap_verification_fail;
	import white.Roadmap_verification_success;
	import white.Stat;
	
	/**
	 * ...
	 * @author Sergey Dobarin
	 */
	public dynamic class PresetDefault extends Preset
	{
		public function PresetDefault()
		{
			this[Style.TOP_BAR] = AppTheme.RED_MEDIUM;
			this[Style.TOP_BAR_FONT_SIZE] = Config.TOP_BAR_FONT_SIZE;
			this[Style.TOP_BAR_TEXT_COLOR] = Color.WHITE;
			this[Style.TOP_BAR_ICON_COLOR] = Color.WHITE;
			this[Style.TOP_BAR_TEXT_BOLD] = false;
			this[Style.FILTER_TABS_COLOR_TAB_BG_SELECTED] = 0x6e92af;
			this[Style.FILTER_TABS_COLOR_TAB_TEXT_SELECTED] = 0xFFFFFF;
			this[Style.FILTER_TABS_COLOR_TAB_BG_BORDER_SELECTED] = 0x6e92af;
			this[Style.FILTER_TABS_COLOR_TAB_TEXT] = 0x6e92af;
			this[Style.FILTER_TABS_COLOR_TAB_BG_BORDER] = 0x6e92af;
			this[Style.TOP_BAR_STATUS_TEXT_COLOR] = 0xFFFFFF;
			this[Style.TOP_BAR_FONT_SIZE_SMALL] = Config.TOP_BAR_FONT_SIZE;
			this[Style.TOP_BAR_TEXT_BOLD_SMALL] = false;
			this[Style.BOTTOM_BAR_COLOR] = 0xf7f8f9;
			this[Style.BOTTOM_BAR_LINE] = true;
			this[Style.BOTTOM_BAR_TEXT_COLOR] = Color.GREY;
			this[Style.BOTTOM_BAR_TEXT_SELECTED_COLOR] = Color.RED;
			this[Style.CHAT_BACKGROUND] = 0xc4def1;
			this[Style.MESSAGE_COLOR_SELF] = Color.WHITE;
			this[Style.MESSAGE_RADIUS] = Config.FINGER_SIZE * .1;
			this[Style.MESSAGE_DATE_BACK_ALPHA] = 0.3;
			this[Style.MESSAGE_DATE_COLOR] = Color.WHITE;
			this[Style.STATUS_COLOR] = 0xFDFFFF;
			this[Style.TOP_BAR_ICON_SIZE] = Config.FINGER_SIZE * .45;
			this[Style.CHAT_TOP_ICON_SIZE] = Config.FINGER_SIZE * .38;
			this[Style.ICON_COLOR] = 0x6e92af;
			this[Style.ICON_RIGHT_COLOR] = Color.GREY_LIGHT;
			this[Style.COLOR_BACKGROUND] = Color.WHITE;
			this[Style.COLOR_TITLE] = Color.BLACK_OLD;
			this[Style.COLOR_LIST_SELECTED] = Color.WHITE;
			this[Style.COLOR_LIST_SPECIAL] = Color.GREY_SUPER_LIGHT;
			this[Style.COLOR_SUBTITLE] = 0x363E4E;
			this[Style.FILTER_TABS_COLOR_BACKGROUND] = Color.WHITE;
			this[Style.COLOR_TIP_BACKGROUND] = 0xDEE8F2;
			this[Style.COLOR_TIP_TEXT] = 0x6E92AF;
			this[Style.COLOR_ICON_LIGHT] = 0xC5D1DB;
			this[Style.COLOR_TEXT] = AppTheme.GREY_DARK;
			this[Style.COLOR_SEPARATOR] = Color.GREY_SUPER_LIGHT;
			this[Style.COLOR_SEPARATOR_TOP_BAR] = Color.GREY_SSL;
			this[Style.COLOR_ICON_SETTINGS] = Color.GREY;
			this[Style.COLOR_BUTTON_RED_DOWN] = Color.RED_DARK;
			this[Style.COLOR_BUTTON_TEXT] = Color.WHITE;
			this[Style.COLOR_BUTTON_RED] = Color.RED;
			this[Style.BANK_BACKGROUND_ID] = "7";
			this[Style.COLOR_CHAT_MESSAGE_BACKGROUND] = Color.WHITE;
			this[Style.COLOR_CHAT_MESSAGE_LINE] = Color.GREY_SUPER_LIGHT;
			this[Style.COLOR_CHAT_MESSAGE_MENU] = Color.RED;
			this[Style.COLOR_INPUT_BACKGROUND] = Color.WHITE;
			this[Style.COLOR_ICON_SPECIAL] = Color.GREY;
			this[Style.COLOR_TIP_BACKGROUND_SPECIAL] = Color.GREY_SSL;
			this[Style.COLOR_LINE] = Color.GREY;
			this[Style.TOGGLER_UNSELECTED] = Color.GREY_LIGHT;
			this[Style.TOGGLER_UNSELECTED_DOWN] = Color.GREY;
			this[Style.COLOR_STICKERS_MENU_BACKGROUND] = 0xECEEEF;
			this[Style.MESSAGE_COLOR] = Color.WHITE;
			this[Style.BOTTOM_BAR_SELECTED_BACKGROUND] = NaN;
			this[Style.COLOR_TIPS_911_BACKGROUND] = 0xF6F7F2;
			this[Style.COLOR_911_BRED] = 0x0000EE;
			this[Style.COLOR_BACKGROUND_LIGHT] = 0xF6F7F2;
			this[Style.COLOR_TIPS] = Color.RED;
			this[Style.COLOR_LINE_LIGHT] = Color.GREY_LIGHT;
			this[Style.COLOR_LINE_SSL] = Color.GREY_SSL;
			this[Style.COLOR_911_MARK_TEXT] = 0x1168E9;
			this[Style.COLOR_911_MARK_BACK] = 0xE7F0FD;
			this[Style.ITALIC_911_MARK_TEXT] = true;
			
			this[Style.COLOR_ROADMAP_ACTIVE] = Color.GREEN;
			this[Style.COLOR_ROADMAP_DONE] = Color.GREEN;
			this[Style.COLOR_ROADMAP_FAIL] = Color.RED;
			this[Style.COLOR_ROADMAP_INACTIVE] = Color.GREY_LIGHT;
			
			this[Style.MENU_CHATS] = SWFMainMenuIconChats2;
			this[Style.MENU_CONTACTS] = SWFMainMenuIconContacts;
			this[Style.MENU_BANK] = SWFMainMenuIconPay;
			this[Style.MENU_BOT] = SWFMainMenuIconBot;
			this[Style.MENU_SETTINGS] = SWFMainMenuIconSettings;
			this[Style.MENU_CHATS_SELECTED] = SWFMainMenuIconChatsSelected2;
			this[Style.MENU_CONTACTS_SELECTED] = SWFMainMenuIconContactsSelected;
			this[Style.MENU_BANK_SELECTED] = SWFMainMenuIconPaySelected;
			this[Style.MENU_BOT_SELECTED] = SWFMainMenuIconBotSelected;
			this[Style.MENU_SETTINGS_SELECTED] = SWFMainMenuIconSettingsSelected;
			this[Style.LIGHT_STATUS_BAR] = true;
			
			this[Style.ICON_911] = Icon911;
			this[Style.ICON_SETTINGS] = IconSettingsS;
			this[Style.ICON_CALLS] = IconCallsS;
			this[Style.ICON_REFRESH] = SWFPaymentsRefreshIcon;
			this[Style.ICON_GROUP_CHAT] = IconGroupChat;
			this[Style.ICON_MARKETPLACE] = SWFUpDownArrows;
			this[Style.ICON_BOT] = SWFSwissFlagGray;
			this[Style.ICON_BANK] = SWFIconBank;
			this[Style.ICON_LOCK] = SWFLockButonBasic;
			this[Style.ICON_UNLOCK] = SWFUnlockButonBasic;
			this[Style.ICON_SMILE] = IconSmile;
			this[Style.ICON_ATTACH] = SWFIconChatAttach;
			this[Style.ICON_SMILE_COLOR] = IconSmileColor;
			this[Style.ICON_MIC] = SWFUnlockButonBasic;
			this[Style.ICON_STICKER] = IconDog;
			this[Style.ICON_STICKER_COLOR] = IconDogColor;
			this[Style.ICON_ATTACH_COLOR] = 0xC5D2DB;
			this[Style.ICON_SEND] = SWFIconSend;
			this[Style.ICON_SEND_VOICE] = SendButtonSound;
			this[Style.ICON_NOTIFICATIONS] = SWFSettingsIcon_notification;
			this[Style.ICON_SOUND_MESSAGES] = SWFSettingsIcon_messagessound;
			this[Style.ICON_SOUND_CALL] = SWFSettingsIcon_callssound;
			this[Style.ICON_LANGUAGE] = SetLanguagesIcon;
			this[Style.ICON_SOCIAL] = SWFSocialIcon;
			this[Style.ICON_RATING] = SWFSettingsIcon_stats;
			this[Style.ICON_REFERRAL] = AddUserToChatIcon;
			this[Style.ICON_LOGOUT] = SWFSettingsIcon_logout;
			this[Style.ICON_COMMUNITY] = CommunityIconGrey;
			this[Style.ICON_JAIL] = JailIconRound;
			this[Style.ICON_PROTECTION] = ProtectionIcon;
			this[Style.ICON_PAID_CHAT] = PaidChatIcon;
			this[Style.ICON_ONE_CLICK] = OneClick;
			this[Style.ICON_STAT] = Stat;
			this[Style.ICON_BLOCK_USER] = BlockUserIcon;
			this[Style.ICON_BAN] = SWFSettingsIcon_ban;
			this[Style.ICON_BAN_FOREVER] = SettingsIcon_banForever;
			this[Style.ICON_ZERO_RATING] = SWFSettingsIcon_nomoney;
			this[Style.ICON_FLOWER] = FlowerIcon;
			this[Style.ICON_ADD_USER] = AddUserToChatIcon;
			this[Style.ICON_EDIT] = EditIcon;
			this[Style.ICON_FILE] = IconSendFiles;
			this[Style.ICON_BACK] = IconBack;
			this[Style.ICON_MAKE_CALL] = PhoneIconGrey;
			this[Style.ICON_ZOOM] = PhoneIconGrey;
			this[Style.ICON_INFO] = IconInfoClip;
			this[Style.ICON_ADD] = AddItemButton;
			this[Style.ICON_GEO] = GeopositionIcon;
			this[Style.ICON_ATTACH_CAMERA] = AttachCamIcon;
			this[Style.ICON_ATTACH_GALLERY] = AttachImageIcon;
			this[Style.ICON_ATTACH_MONEY] = AttachPayIcon;
			this[Style.ICON_ATTACH_INVOICE] = AttachInvoiceIcon;
			this[Style.ICON_ATTACH_PUZZLE] = attachIconPuzzle;
			this[Style.ICON_ATTACH_GIFT] = SendGiftIcon;
			this[Style.ICON_ATTACH_VIDEO] = attachIconVideo;
			this[Style.ICON_ARROW_DOWN] = SWFDoubleArrowsDown;
			this[Style.ICON_ARROW_UP] = SWFDoubleArrowsUp;
			this[Style.ICON_JAILED] = JailIcon;
			this[Style.ICON_FILTERS] = FilterSmallIcon;
			this[Style.ICON_CHAT] = white.ChatIcon;
			this[Style.ICON_PHONEBOOK] = PhonebookIcon;
			
			this[Style.ICON_ROADMAP_FORM_ACTIVE] = Roadmap_form;
			this[Style.ICON_ROADMAP_FORM_DONE] = Roadmap_form_success;
			this[Style.ICON_ROADMAP_FORM_FAIL] = Roadmap_form_fail;
			
			this[Style.ICON_ROADMAP_SCAN_ACTIVE] = Roadmap_scan;
			this[Style.ICON_ROADMAP_SCAN_DONE] = Roadmap_scan_success;
			this[Style.ICON_ROADMAP_SCAN_FAIL] = Roadmap_scan_fail;
			
			this[Style.ICON_ROADMAP_SOLVENCY_ACTIVE] = Roadmap_solvency;
			this[Style.ICON_ROADMAP_SOLVENCY_DONE] = Roadmap_solvency_success;
			this[Style.ICON_ROADMAP_SOLVENCY_FAIL] = Roadmap_solvency_fail;
			
			this[Style.ICON_ROADMAP_DEPOSIT_ACTIVE] = Roadmap_deposit;
			this[Style.ICON_ROADMAP_DEPOSIT_DONE] = Roadmap_deposit_success;
			this[Style.ICON_ROADMAP_DEPOSIT_FAIL] = Roadmap_deposit_fail;
			
			this[Style.ICON_ROADMAP_SELECT_CARD_ACTIVE] = Roadmap_card;
			this[Style.ICON_ROADMAP_SELECT_CARD_DONE] = Roadmap_card_success;
			this[Style.ICON_ROADMAP_SELECT_CARD_FAIL] = Roadmap_card_fail;
			
			this[Style.ICON_ROADMAP_VIDEOIDENTIFICATION_ACTIVE] = Roadmap_verification;
			this[Style.ICON_ROADMAP_VIDEOIDENTIFICATION_DONE] = Roadmap_verification_success;
			this[Style.ICON_ROADMAP_VIDEOIDENTIFICATION_FAIL] = Roadmap_verification_fail;
			
			this[Style.ICON_ROADMAP_APPROVE_ACCOUNT_ACTIVE] = Roadmap_approve;
			this[Style.ICON_ROADMAP_APPROVE_ACCOUNT_DONE] = Roadmap_approve_success;
			this[Style.ICON_ROADMAP_APPROVE_ACCOUNT_FAIL] = Roadmap_approve_fail;
			this[Style.ICON_TEXT] = white.Text;
			this[Style.ICON_TOUCH_ID] = TouchIdIcon;
			this[Style.ICON_FACE_ID] = FaceIdIcon;
			this[Style.CONTROL_TEXT_SIZE] = Config.FINGER_SIZE * .3;
			this[Style.CONTROL_TEXT_SMALL_SIZE] = Config.FINGER_SIZE * .25;
			this[Style.SIZE_BUTTON_CORNER] = Config.FINGER_SIZE * .3;
			this[Style.SIZE_BUTTON_HEIGHT] = Config.FINGER_SIZE * .8;
			this[Style.COLOR_TEXT_DISABLE] = Color.GREY_LIGHT;
			this[Style.CONTROL_INACTIVE] = Color.GREY_LIGHT;
			this[Style.ERROR_COLOR] = Color.RED;
			this[Style.PAYMENTS_LOGIN_IMAGE] = PaymentsImageWhite;
			this[Style.PAYMENTS_LOGIN_BACK_COLOR] = 0xFFE6F5;
			this[Style.COLOR_IOS_ACTION_SHEET_BACK] = 0xFFFFFF;
			this[Style.COLOR_IOS_ACTION_SHEET_ITEM_BACK] = 0xF9F9F9;
			this[Style.ALPHA_IOS_ACTION_SHEET_BACK] = 0.88;
			this[Style.RADIUS_IOS_ACTION_SHEET_BACK] = Config.FINGER_SIZE * .23;
			this[Style.HEIGHT_IOS_ACTION_SHEET_BACK] = Config.FINGER_SIZE * 1.0;
			this[Style.ICON_PAYMENTS_LOGO] = PaymentsLogo;
			this[Style.ICON_LOGIN_LOGO] = LoginLogo;
			this[Style.COLOR_KEYBOARD_TEXT] = Color.BLUE_DARK_2;
			this[Style.COLOR_PHONE] = Color.BLUE_2;
			this[Style.ICON_ATTACH_FILE] = AttachFileIcon;
			this[Style.COLOR_POPUP_HEADER] = Color.GREY_SUPER_LIGHT;
			this[Style.COLOR_BUTTON_SECONDARY] = Color.GREY;
			this[Style.COLOR_TOGGLER] = Color.WHITE;
			this[Style.ROADMAP_ILLUSTRATION] = RoadmapImage;
			this[Style.PAYMENT_VISA] = VisaClip;
			this[Style.TRANSFER_ILLUSTRATION] = TransferIllustration;
			this[Style.ICON_ATTACH_DEAL] = CreateDealIcon;
			this[Style.COLOR_BUTTON_OUTLINE] = Color.GREY_LIGHT;
			this[Style.FLOAT_POOPUP_RADIUS] = int(Config.FINGER_SIZE * .6);
			this[Style.BUTTON_PADDING] = int(Config.FINGER_SIZE * .23);
			this[Style.COLOR_BUTTON_ACCENT] = Color.GREY_DARK;
			this[Style.COLOR_SEEK_BACK] = Color.GREY_SSL;
			this[Style.COLOR_TEXT_RED_DARK] = Color.RED_DARK;
			this[Style.COLOR_RED_LIGHT] = Color.RED_LIGHT;
			this[Style.ICON_TRASH] = ContectDeleteIcon;
			this[Style.COLOR_ACCENT_PANEL] = Color.GREY_DARK;
			
			this[Style.SCREEN_PADDING_LEFT] = int(Config.FINGER_SIZE * .2);
			this[Style.ICON_STREAM] = StartStreamIcon;
			this[Style.ICON_UNSUBSCRIBE] = OwnerIcon;
			this[Style.ICON_SUBSCRIBE] = ownerIconOutline;
			
			this[Style.MENU_P2P] = Menu911;
			this[Style.MENU_P2P_SELECTED] = Menu911Selected;
		}
	}
}